# SPDX-License-Identifier: GPL-3.0-or-later
"""Verified GitHub ZIP updates; transactions operate on the running app directory.

This module intentionally has no Qt imports. A private copy runs after the GUI
has saved its data and exited. It never executes code from an unverified ZIP.
"""
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import re
import shutil
import ssl
import stat
import subprocess
import sys
import tempfile
import time
from urllib.error import HTTPError
from urllib.parse import urlsplit, unquote
from urllib.request import Request, build_opener, HTTPSHandler, HTTPRedirectHandler
import zipfile

REPOSITORY = 'PianothShaveck/yun-jin-companion'
RELEASES_URL = 'https://github.com/' + REPOSITORY + '/releases'
API_URL = 'https://api.github.com/repos/' + REPOSITORY + '/releases/latest'
INTERVAL = 2 * 60 * 60
MAX_ZIP = 200 * 1024 * 1024
MAX_EXPANDED = 600 * 1024 * 1024
MANIFEST = 'release-manifest.json'
PROTOCOL = 1


def version_tuple(value):
    match = re.fullmatch(r'v?(\d+)\.(\d+)\.(\d+)', str(value))
    if not match:
        raise ValueError('Versione stabile non riconosciuta: ' + str(value))
    return tuple(map(int, match.groups()))


def github_url(url, download=False):
    parsed = urlsplit(url)
    if parsed.scheme != 'https' or parsed.username or parsed.password or parsed.port not in (None, 443):
        return False
    host = (parsed.hostname or '').lower()
    if download and host in ('release-assets.githubusercontent.com', 'objects.githubusercontent.com'):
        return True
    return (host == 'github.com' and
            unquote(parsed.path).startswith('/' + REPOSITORY + '/releases/'))


class SafeRedirect(HTTPRedirectHandler):
    def redirect_request(self, request, fp, code, msg, headers, newurl):
        if not github_url(newurl, download=True):
            raise ValueError('Destinazione del download non autorizzata.')
        return super().redirect_request(request, fp, code, msg, headers, newurl)


def open_url(url):
    context = ssl.create_default_context()
    try:
        import certifi
        # Add Mozilla roots without discarding system/enterprise certificates.
        context.load_verify_locations(cafile=certifi.where())
    except ImportError:
        pass
    opener = build_opener(HTTPSHandler(context=context), SafeRedirect())
    return opener.open(Request(url, headers={
        'User-Agent': 'Yun-Jin-Companion-Updater',
        'Accept': 'application/vnd.github+json' if url == API_URL else 'application/octet-stream',
        'X-GitHub-Api-Version': '2026-03-10',
    }), timeout=25)


def release_from_json(data, current):
    if data.get('draft') or data.get('prerelease'):
        return None
    version = version_tuple(data.get('tag_name', ''))
    if version <= version_tuple(current):
        return None
    number = '.'.join(map(str, version))
    # Source ZIPs and GitHub's autogenerated archives are deliberately excluded.
    name = 'Yun-Jin-Companion-' + number + '.zip'
    assets = [a for a in data.get('assets', []) if a.get('name') == name and a.get('state') == 'uploaded']
    page = data.get('html_url', '')
    if not github_url(page):
        raise ValueError('Indirizzo della release non valido.')
    result = dict(version=number, notes=str(data.get('body') or 'Nessuna nota di rilascio pubblicata.'),
                  url=page, name=name, automatic=False, reason='Il pacchetto ZIP non è ancora disponibile.')
    if len(assets) != 1:
        return result
    asset = assets[0]
    digest = asset.get('digest') or ''
    url = asset.get('browser_download_url', '')
    size = asset.get('size', 0)
    if not github_url(url) or not 0 < size <= MAX_ZIP:
        raise ValueError('Pacchetto di aggiornamento non valido.')
    result.update(download=url, size=size)
    if not re.fullmatch(r'sha256:[0-9a-fA-F]{64}', digest):
        result['reason'] = 'GitHub non ha ancora fornito la verifica SHA-256 del pacchetto. Riprova più tardi.'
        return result
    result.update(automatic=True, digest=digest[7:].lower(), reason='')
    return result


def check_release(current):
    try:
        with open_url(API_URL) as response:
            raw = response.read(2 * 1024 * 1024 + 1)
    except HTTPError as exc:
        if exc.code == 404:
            return None
        if exc.code in (403, 429):
            raise RuntimeError('GitHub ha limitato le richieste. Riprova più tardi.') from exc
        raise
    if len(raw) > 2 * 1024 * 1024:
        raise ValueError('Risposta di GitHub troppo grande.')
    return release_from_json(json.loads(raw), current)


def safe_relative(name):
    p = PurePosixPath(name)
    if (not name or '\\' in name or ':' in name or '\x00' in name or p.is_absolute()
            or any(part in ('', '.', '..') for part in name.split('/'))):
        raise ValueError('Percorso non sicuro nel pacchetto: ' + repr(name))
    return p


def sha256(path):
    h = hashlib.sha256()
    with Path(path).open('rb') as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b''):
            h.update(chunk)
    return h.hexdigest()


def read_manifest(root, manifest_path=None):
    doc = json.loads((Path(manifest_path) if manifest_path else Path(root) / 'app' / MANIFEST).read_text(encoding='utf-8'))
    if doc.get('protocol') != PROTOCOL or not isinstance(doc.get('files'), dict):
        raise ValueError('Formato di aggiornamento non supportato. Usa l’installer della nuova release.')
    version_tuple(doc['version'])
    if not doc['files'] or len(doc['files']) > 3000:
        raise ValueError('Elenco dei file non valido.')
    for name, digest in doc['files'].items():
        safe_relative(name)
        if not re.fullmatch(r'[0-9a-f]{64}', digest):
            raise ValueError('Hash dei file non valido.')
        if not (name.startswith(('app/', 'installer/')) or name in ('Guida.pdf', 'Mac.command', 'Linux.sh', 'Windows.cmd')):
            raise ValueError('File estraneo al programma: ' + name)
    required = {'app/yun_jin_pet.py', 'app/yun_jin_app.py', 'app/yun_jin_platform.py',
                'app/assets/animations.json', 'app/spritesheet-yun-jin-v2.png', 'Guida.pdf'}
    if not required <= doc['files'].keys():
        raise ValueError('Il pacchetto non contiene tutti i file essenziali.')
    return doc


def verify_program(root, expected_version=None):
    doc = read_manifest(root)
    if expected_version and doc['version'] != expected_version:
        raise ValueError('La versione nello ZIP non corrisponde alla release.')
    for name, digest in doc['files'].items():
        path = Path(root) / name
        if path.is_symlink() or not path.is_file() or sha256(path) != digest:
            raise ValueError('File mancante o danneggiato: ' + name)
    return doc


def unpack_verified(archive, destination, expected_version):
    destination = Path(destination)
    with zipfile.ZipFile(archive) as z:
        infos = z.infolist()
        if not infos or len(infos) > 4000 or sum(i.file_size for i in infos) > MAX_EXPANDED:
            raise ValueError('Dimensioni del pacchetto non valide.')
        roots, seen = set(), set()
        for info in infos:
            name = info.filename.rstrip('/')
            path = safe_relative(name)
            mode = info.external_attr >> 16
            if stat.S_ISLNK(mode) or (stat.S_IFMT(mode) not in (0, stat.S_IFREG, stat.S_IFDIR)):
                raise ValueError('Collegamenti o file speciali non ammessi nello ZIP.')
            key = name.casefold()
            if key in seen:
                raise ValueError('Percorso duplicato nel pacchetto.')
            seen.add(key); roots.add(path.parts[0])
        if len(roots) != 1:
            raise ValueError('Struttura ZIP non riconosciuta.')
        for info in infos:
            path = destination / info.filename
            if info.is_dir():
                path.mkdir(parents=True, exist_ok=True)
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                with z.open(info) as src, path.open('wb') as dst:
                    shutil.copyfileobj(src, dst)
                path.chmod(0o755 if info.filename.endswith(('.command', '.sh')) else 0o644)
    root = destination / next(iter(roots))
    verify_program(root, expected_version)
    return root


def check_compatibility(manifest):
    from importlib.metadata import version, PackageNotFoundError
    minimum = tuple(manifest.get('python_min', [3, 10]))
    maximum = tuple(manifest.get('python_max_exclusive', [3, 15]))
    if not minimum <= sys.version_info[:2] < maximum:
        raise RuntimeError('Questa release richiede un’altra versione di Python. Apri la release e usa il suo installer.')
    requirements = manifest.get('requirements')
    if not isinstance(requirements, dict) or not requirements:
        raise ValueError('Requisiti del pacchetto mancanti.')
    for package, wanted in requirements.items():
        try:
            actual = version(package)
        except PackageNotFoundError:
            actual = None
        if actual != wanted:
            raise RuntimeError('Questa release aggiorna anche le dipendenze. Apri la release e usa il suo installer.')


def prepare_update(release, cache, progress=lambda value: None):
    if not release.get('automatic'):
        raise ValueError(release.get('reason', 'Pacchetto non verificabile.'))
    cache = Path(cache); cache.mkdir(parents=True, exist_ok=True)
    work = Path(tempfile.mkdtemp(prefix='update-', dir=cache))
    try:
        archive = work / 'release.zip'
        total, digest = 0, hashlib.sha256()
        with open_url(release['download']) as src, archive.open('wb') as dst:
            while True:
                chunk = src.read(256 * 1024)
                if not chunk:
                    break
                total += len(chunk)
                if total > MAX_ZIP or total > release['size']:
                    raise ValueError('Dimensione del download inattesa.')
                digest.update(chunk); dst.write(chunk)
                progress(min(95, int(95 * total / release['size'])))
        if total != release['size'] or digest.hexdigest() != release['digest']:
            raise ValueError('Verifica SHA-256 fallita. Nessun file è stato modificato.')
        source = unpack_verified(archive, work / 'unpacked', release['version'])
        check_compatibility(read_manifest(source))
        progress(100)
        return str(source)
    except BaseException:
        shutil.rmtree(work, ignore_errors=True)
        raise


def destination_for(name, app_dir):
    relative = safe_relative(name)
    app_dir = Path(app_dir).resolve()
    return app_dir / Path(*relative.parts[1:]) if relative.parts[0] == 'app' else app_dir.parent / name


def assert_regular_destination(path, root):
    path, root = Path(path), Path(root)
    path.relative_to(root)
    for candidate in (path, *path.parents):
        if candidate == root.parent:
            break
        if candidate.is_symlink():
            raise ValueError('Il percorso contiene un collegamento simbolico: ' + str(candidate))
    if path.exists() and not path.is_file():
        raise ValueError('Il percorso di destinazione non è un file: ' + str(path))


def atomic_copy(source, destination):
    destination.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix='.yun-jin-new-', dir=destination.parent)
    os.close(fd)
    try:
        shutil.copy2(source, tmp)
        os.replace(tmp, destination)
    finally:
        Path(tmp).unlink(missing_ok=True)


def transaction(source, app_dir, backup, journal_path):
    """Replace only managed files; unknown/user files and the data directory stay.

    A durable journal is written before the first mutation. It permits recovery
    after an interrupted update as well as rollback after an ordinary error.
    """
    source, app_dir, backup = Path(source), Path(app_dir).resolve(), Path(backup)
    new = verify_program(source)
    portable = (app_dir.parent / 'installer/install.py').is_file()
    def managed(name):
        return name.startswith('app/') or name == 'Guida.pdf' or portable
    names = {name for name in new['files'] if managed(name)} | {'app/' + MANIFEST}
    old_path = app_dir / MANIFEST
    if old_path.is_file():
        old = read_manifest(app_dir.parent, old_path)
        names.update(name for name in old['files'] if managed(name))
    entries = []
    for name in sorted(names):
        dest = destination_for(name, app_dir)
        assert_regular_destination(dest, app_dir.parent)
        existed = dest.is_file()
        if existed:
            saved = backup / name
            saved.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(dest, saved)
        entries.append({'name': name, 'existed': existed})
    journal = dict(app_dir=str(app_dir), backup=str(backup), entries=entries,
                   version=new['version'], status='applying')
    write_json(journal_path, journal)
    try:
        for item in entries:
            dest = destination_for(item['name'], app_dir)
            src = source / item['name']
            if item['name'] in new['files'] or item['name'] == 'app/' + MANIFEST:
                atomic_copy(src, dest)
            else:
                dest.unlink(missing_ok=True)
        journal['status'] = 'installed'
        write_json(journal_path, journal)
    except BaseException:
        rollback(journal_path)
        raise
    return journal


def write_json(path, data):
    path = Path(path)
    tmp = path.with_suffix('.new')
    with tmp.open('w', encoding='utf-8') as stream:
        json.dump(data, stream, ensure_ascii=False, indent=2)
        stream.flush(); os.fsync(stream.fileno())
    os.replace(tmp, path)


def rollback(journal_path):
    journal = json.loads(Path(journal_path).read_text(encoding='utf-8'))
    app_dir, backup = Path(journal['app_dir']), Path(journal['backup'])
    for item in reversed(journal['entries']):
        dest = destination_for(item['name'], app_dir)
        assert_regular_destination(dest, app_dir.parent)
        if item['existed']:
            atomic_copy(backup / item['name'], dest)
        else:
            dest.unlink(missing_ok=True)
    journal['status'] = 'rolled_back'
    write_json(journal_path, journal)


def clear_pending(work):
    pending = Path(work).parent / 'pending.json'
    if pending.is_file():
        data = json.loads(pending.read_text(encoding='utf-8'))
        if Path(data.get('work', '')).resolve() == Path(work).resolve():
            pending.unlink()


def recover_pending(app_dir, data_root):
    """Pre-import recovery after power loss. Never recover under a live app.

    Return 'restart' after rollback so the launcher reloads the old modules.
    The authenticated restart launched by our worker bypasses this function.
    """
    if os.environ.get('YUN_JIN_UPDATE_READY'):
        return 'ok'
    app_dir, data_root = Path(app_dir).resolve(), Path(data_root).resolve()
    pending = data_root / 'updates/pending.json'
    if not pending.is_file():
        return 'ok'
    data = json.loads(pending.read_text(encoding='utf-8'))
    if Path(data['app_dir']).resolve() != app_dir:
        return 'ok'
    work = Path(data['work']).resolve()
    work.relative_to((data_root / 'updates').resolve())
    journal_path = work / 'journal.json'
    if not journal_path.is_file():
        return 'ok'  # Download/preparation never touched program files.
    from PyQt6.QtCore import QLockFile
    lock = QLockFile(str(data_root / 'companion.lock')); lock.setStaleLockTime(0)
    if not lock.tryLock(100):
        return 'busy'
    try:
        journal = json.loads(journal_path.read_text(encoding='utf-8'))
        if Path(journal['app_dir']).resolve() != app_dir:
            raise ValueError('Destinazione di recupero non corrispondente.')
        Path(journal['backup']).resolve().relative_to(work)
        if journal['status'] == 'applying':
            rollback(journal_path)
            write_json(work / 'result.json', dict(ok=False, message='Aggiornamento interrotto: ripristinata la versione precedente.'))
            os.environ['YUN_JIN_UPDATE_RESULT'] = str(work / 'result.json')
            clear_pending(work)
            return 'restart'
        clear_pending(work)
        return 'ok'
    finally:
        lock.unlock()


def launch(executable, app_dir, result_file, token=None, ready=None):
    env = os.environ.copy()
    env['YUN_JIN_UPDATE_RESULT'] = str(result_file)
    if ready:
        env['YUN_JIN_UPDATE_READY'] = str(ready)
        env['YUN_JIN_UPDATE_TOKEN'] = token
    else:
        env.pop('YUN_JIN_UPDATE_READY', None)
        env.pop('YUN_JIN_UPDATE_TOKEN', None)
    args = [str(executable), str(Path(app_dir) / 'yun_jin_pet.py')]
    kwargs = {'cwd': str(app_dir), 'env': env, 'stdin': subprocess.DEVNULL}
    log = open(Path(result_file).parent / 'worker.log', 'ab')
    kwargs.update(stdout=log, stderr=log)
    if sys.platform == 'win32':
        kwargs['creationflags'] = subprocess.CREATE_NO_WINDOW | subprocess.CREATE_NEW_PROCESS_GROUP
    else:
        kwargs['start_new_session'] = True
    try:
        return subprocess.Popen(args, **kwargs)
    finally:
        log.close()


def worker(plan_path):
    from PyQt6.QtCore import QCoreApplication, QLockFile
    app = QCoreApplication([])
    plan = json.loads(Path(plan_path).read_text(encoding='utf-8'))
    work = Path(plan_path).parent
    result, ready = work / 'result.json', work / 'ready.txt'
    lock = QLockFile(plan['lock']); lock.setStaleLockTime(0)
    write_json(work / 'worker-ready.json', {'ready': True})
    deadline = time.monotonic() + 120
    while not lock.tryLock(100):
        if (work / 'cancel').exists() or time.monotonic() >= deadline:
            return 2  # Original app did not close: don't change or relaunch it.
        time.sleep(.15)
    try:
        if (work / 'cancel').exists():
            return 2
        transaction(plan['source'], plan['app_dir'], work / 'backup', work / 'journal.json')
        write_json(result, dict(ok=True, version=plan['version']))
    except Exception as exc:
        write_json(result, dict(ok=False, message=str(exc)))
        lock.unlock()
        launch(plan['executable'], plan['app_dir'], result)
        return 1
    lock.unlock()
    child = launch(plan['executable'], plan['app_dir'], result, plan['token'], ready)
    deadline = time.monotonic() + 60
    while time.monotonic() < deadline:
        if ready.is_file() and ready.read_text(encoding='utf-8') == plan['token']:
            journal_path = work / 'journal.json'
            journal = json.loads(journal_path.read_text(encoding='utf-8'))
            journal['status'] = 'committed'; write_json(journal_path, journal)
            clear_pending(work)
            return 0
        if child.poll() is not None:
            break
        time.sleep(.2)
    # Only stop the process we just launched. Never touch another user process.
    if child.poll() is None:
        child.terminate()
        try:
            child.wait(timeout=10)
        except subprocess.TimeoutExpired:
            # Don't restore underneath a process that is still alive.
            write_json(result, dict(ok=False, message='Riavvio non completato. Chiudi Yun Jin e riprova.'))
            return 3
    if not lock.tryLock(5000):
        return 3
    try:
        rollback(work / 'journal.json')
        write_json(result, dict(ok=False, message='La nuova versione non si è avviata. Ripristinata la versione precedente.'))
    finally:
        lock.unlock()
    launch(plan['executable'], plan['app_dir'], result)
    return 1


if __name__ == '__main__':
    if len(sys.argv) == 3 and sys.argv[1] == '--worker':
        sys.exit(worker(sys.argv[2]))
    raise SystemExit('Use --worker PLAN.json')
